openapi: 3.0.1
info:
  title: test-jwt-validation
  version: '1.0'
servers:
  - url: https://azure-apim-kt.azure-api.net/jwt-validation
paths:
  /*:
    get:
      summary: all
      description: all
      operationId: all
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]